[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  functions = "functions"
  publish = "dist"
  port = 8888
  targetPort = 5174

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
